name: Docker Image Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          # Replace with your new ACR login server and repository name
          docker build . --file WebApp.Dockerfile --tag ${{ secrets.PROJECTASSISTANT_ACR_LOGIN_SERVER }}/projectassistant:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER
