name: Build Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    # Set up Node.js environment
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    # Install dependencies
    - run: npm ci

    # Build the project
    - run: NODE_OPTIONS=--max_old_space_size=8192 npm run build --if-present

    # Debugging Step: Verify that static directory exists after the build
    - name: List Static Directory Contents
      run: ls -al ../static || echo "Static directory not found!"

    # Create a deployment package (zip the contents of the static folder)
    - name: Create deployment zip
      run: |
        cd ../static
        zip -r ../static.zip .

    # Debugging Step: Verify the contents of the deployment zip
    - name: List contents of deployment zip
      run: unzip -l ../static.zip

    # Deploy the zip to Azure Web App
    - name: Deploy to Azure Web App
      if: github.ref == 'refs/heads/main'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'project-assistant'  # Replace with your Azure App Service name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./static.zip
